### ISSUE TITLE
Pets Not Deleting

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#37] opened 2022-04-24 21:32 UTC
Seems the pets dont properly delete out of a list. I removed 2 "cats:entity-tamed-cat" (or something like that) from my list yesterday. They came back, i removed them again but could still see 2 random extra "Cat (male)"s in a nest. Today both are back and now the dog i had taming duplicated lol

**Comment by G3rste** [comment] 2022-04-29 18:08
I made these commands as some kind of emergency solution that only messes with entity despawing if really necessary. This is how they are supposed to work.
- Remove: Removes a pet from the petmanagers list. However if the pet is still alive, It will add itself to the list the next time it is loaded. I made this to allow admins to remove the spam of currupted pets that occured in previous versions when pets would despawn but remain in the petmanager.
- Forcerespawn: Respawns the pet if there is any possibility to do so. It will use the default respawn method if the entity is dead. However, if the data for this is not found, it will try to spawn a new entity of this type and assign it to the same owner. If the entity you are using this on is still alive you might get duplicates.

I thought about creating a system to despawn pets if remove is execute and to eliminate duplicates after force respawning. However that would have meant possible random mass despawning of peoples pets if I fuck something up and that is a risk I am not willing to take as of now. 

Judging by your comment I am not completely sure if you actually used the forcerespawn to duplicate your dog or if it was duplicated by other means. Could you specify that?

**Comment by RogueRaiden** [comment] 2022-04-29 21:35
the dog duplicated in the list on its own, i didnt touch it.

and alright, i'll keep playing around with it. one of my players had 6 cats named the same in their list, although they only ever tamed 1 cat.

**Comment by G3rste** [comment] 2022-05-01 21:28
Hm interesting. 
Do all these cats have different ids too?
I did a quick check and could not reproduce any of this behavior.
Could you provide me with the exact wording of the commands you used?
While testing around I noticed that I have no specific message if the command was recognised and handled correctly, so maybe I should do a small rework on that end.

**Comment by RogueRaiden** [comment] 2022-05-31 08:36
the player with 6 duplicated cats all have different ids.

the unnamed cats that wont delete have separate ids and keep the same id number when they come back. i tried deleting them again, and they came back. the dog i had that duplicated, the duplicated one was named the same so there where two dogs named "lucky". renamed the real one, and deleted the duplicate just fine without affecting the real one.

it looks like unnamed pets wont delete? lol

the commands i ran were:
/petmanager list rogueraiden
/petmanager delete petID
/pet manager list rogueraiden

**Comment by G3rste** [comment] 2022-07-28 20:31
I have decided that messing with core game mechanics is a dumb idea bound to failure. I reworked the way your pets can respawn. This new system should be self-explanatory and way more intuitive.

**Closed as completed** 2022-07-28 20:32 UTC
Labels: bug
